name: 'container-action'
description: 'github docker container action'
inputs:
  input-name:
    description: 'input name for the greetings message'
    required: true
  serivce-file:
    description: 'yaml file for the config/schema'
    required: true
    default: '.oblivious/service.yaml'
outputs:
  file_exists:
    description: 'flag to indicate if services.yaml exists'
  file_contents:
    description: 'contents of the file'
  dir_hash:
    description: 'hash for all of the files in the current directory'
  echo_log:
    description: 'output of the echo-message.py'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-name }}
    - ${{ inputs.serivce-file }}